export const countries = [
  { name: "Argentina", code: "AR", flag: "🇦🇷" },
  { name: "Arab Emirates", code: "AE", flag: "🇦🇪" },
  { name: "Australia", code: "AU", flag: "🇦🇺" },
  { name: "Austria", code: "AT", flag: "🇦🇹" },
  { name: "Belgium", code: "BE", flag: "🇧🇪" },
  { name: "Brazil", code: "BR", flag: "🇧🇷" },
  { name: "Brunai", code: "BN", flag: "🇧🇳" },
  { name: "Canada", code: "CA", flag: "🇨🇦" },
  { name: "Chech", code: "CZ", flag: "🇨🇿" },
  { name: "China", code: "CN", flag: "🇨🇳" },
  { name: "Colombia", code: "CO", flag: "🇨🇴" },
  { name: "Dutch", code: "NL", flag: "🇳🇱" },
  { name: "Equador", code: "EC", flag: "🇪🇨" },
  { name: "France", code: "FR", flag: "🇫🇷" },
  { name: "Germany", code: "DE", flag: "🇩🇪" },
  { name: "Hong Kong", code: "HK", flag: "🇭🇰" },
  { name: "Hungary", code: "HU", flag: "🇭🇺" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩" },
  { name: "Japan", code: "JP", flag: "🇯🇵" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿" },
  { name: "Korea", code: "KR", flag: "🇰🇷" },
  { name: "Malyasia", code: "MY", flag: "🇲🇾" },
  { name: "Mexico", code: "MX", flag: "🇲🇽" },
  { name: "Mongolia", code: "MN", flag: "🇲🇳" },
  { name: "Norway", code: "NO", flag: "🇳🇴" },
  { name: "Peru", code: "PE", flag: "🇵🇪" },
  { name: "Philippines", code: "PH", flag: "🇵🇭" },
  { name: "Portugal", code: "PT", flag: "🇵🇹" },
  { name: "Rumania", code: "RO", flag: "🇷🇴" },
  { name: "Russia", code: "RU", flag: "🇷🇺" },
  { name: "Singapore", code: "SG", flag: "🇸🇬" },
  { name: "Spain", code: "ES", flag: "🇪🇸" },
  { name: "Sweden", code: "SE", flag: "🇸🇪" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭" },
  { name: "Taiwan", code: "TW", flag: "🇹🇼" },
  { name: "United States", code: "US", flag: "🇺🇸" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳" },
];
