export const majors = [
  "Korean Language and Literature",
  "History",
  "Philosophy",
  "British and American Humanities",
  "Law",
  "Political Science and International Relations",
  "Public Administration",
  "Urban and Regional Planning",
  "Real Estate",
  "Journalism",
  "Media Contents",
  "Advertising and Public Relations",
  "Counselling",
  "Economics",
  "International Trade",
  "Business Administration",
  "Accounting",
  "Industrial Management (Evening)",
  "International Business Administration",
  "Electronics and Electrical Engineering",
  "Semiconductor Convergence Engineering",
  "Polymer Science and Engineering",
  "Fiber System Engineering",
  "Civil and Environmental Engineering",
  "Mechanical Engineering",
  "Chemical Engineering",
  "Architecture",
  "Architectural Engineering",
  "Center for Innovative Engineering Education",
  "Faculty, College of Engineering",
  "Software Science",
  "Computer Engineering",
  "Mobile Systems Engineering",
  "Statistics and Data Science",
  "Cybersecurity",
  "Sino-Korean Education",
  "Special Education",
  "Mathematics Education",
  "Science Education",
  "Physical Education",
  "Teaching Education",
  "Ceramic Arts",
  "Visual Communication Design",
  "Fashion Merchandise Design",
  "Theater",
  "Film",
  "Musical",
  "Dance",
  "Piano",
  "Instrumental Music",
  "Vocal Music",
  "Music Composition",
  "Korean Traditional Music",
  "College of Liberal Arts",
  "Chinese Studies",
  "Japanese Studies",
  "Mongolian Studies",
  "Middle Eastern Studies",
  "Vietnamese Studies",
  "German Studies",
  "French Studies",
  "Spanish and Latin American Studies",
  "Russian Studies",
  "Portuguese and Brazilian Studies",
  "English",
  "Global Korean Language",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Food Science & Nutrition",
  "Materials Science and Engineering",
  "Energy Engineering",
  "Management Engineering",
  "Pharmaceutical Engineering",
  "Crop Science and Biotechnology",
  "Animal Resources Science",
  "Environmental Horticulture",
  "Landscape Architecture",
  "Biomedical Systems",
  "Biological Science",
  "Microbiology",
  "Food Engineering",
  "Cosmeceutical Materials",
  "Crafts Design",
  "Oriental Painting",
  "Fine Arts",
  "Sculpture",
  "Literary Creative Writing",
  "Music Technology",
  "Jazz Performance",
  "Singer-Songwriting",
  "Faculty, College of Arts",
  "Recreation and Leisure Sports",
  "Sport Management",
  "Exercise Prescription & Rehabilitation",
  "International Sports Studies",
  "Taekwondo",
  "Golf",
  "Pre-medical Course",
  "Medical Science",
  "Public Policy",
  "Public Policy (Evening)",
  "Social Welfare",
  "Marine Corps Military Studies",
  "Food Resource Economics",
  "Biomedical Laboratory Science",
  "Physical Therapy",
  "Health Administration",
  "Dental Hygiene",
  "Psychology and Psychotherapy",
  "Nursing",
  "Pre-Dentistry",
  "Dentistry",
  "Pharmacy",
];
